export const GET_SPONSOR_OPERATOR = 'CCUM/GET_SPONSOR_OPERATOR';
export const GET_SPONSOR_OPERATOR_FAIL = 'CCUM/GET_SPONSOR_OPERATOR_FAIL';
export const GET_SPONSOR_OPERATOR_SUCCESS = 'CCUM/GET_SPONSOR_OPERATOR_SUCCESS';
