export const GET_TRIP_CODE_INFO = 'BOOKING/GET_TRIP_CODE_INFO';
export const GET_TRIP_CODE_INFO_SUCCESS = 'BOOKING/GET_TRIP_CODE_INFO_SUCCESS';
export const GET_TRIP_CODE_INFO_ERROR = 'BOOKING/GET_TRIP_CODE_INFO_ERROR';
export const UPDATE_BOOKING_DATA = 'BOOKING/UPDATE_BOOKING_DATA';
export const UPDATE_OPEN_ALERT_MESSAGE = 'BOOKING/UPDATE_OPEN_ALERT_MESSAGE';
export const RESET_BOOKING_DATA = 'BOOKING/RESET_BOOKING_DATA';
export const SUBMIT_TICKET = 'BOOKING/SUBMIT_TICKET';
export const SUBMIT_TICKET_SUCCESS = 'BOOKING/SUBMIT_TICKET_SUCCESS';
export const SUBMIT_TICKET_ERROR = 'BOOKING/SUBMIT_TICKET_ERROR';
export const RESET_TRIP_INFO_DATA = 'BOOKING/RESET_TRIP_INFO_DATA';
export const GET_COUNTRY_CODE_RESOURCE_SUCCESS = 'BOOKING/GET_COUNTRY_CODE_RESOURCE_SUCCESS';
export const GET_COUNTRY_CODE_RESOURCE_ERROR = 'BOOKING/GET_COUNTRY_CODE_RESOURCE_ERROR';
export const GET_TRIP_INFO_DETAIL = 'BOOKING/GET_TRIP_INFO_DETAIL';
export const GET_TRIP_INFO_DETAIL_SUCCESS = 'BOOKING/GET_TRIP_INFO_DETAIL_SUCCESS';
export const GET_TRIP_INFO_DETAIL_ERROR = 'BOOKING/GET_TRIP_INFO_DETAIL_ERROR';
export const GET_TRIP_REVIEWS = 'BOOKING/GET_TRIP_REVIEWS';
export const GET_TRIP_REVIEWS_SUCCESS = 'BOOKING/GET_TRIP_REVIEWS_SUCCESS';
export const GET_TRIP_REVIEWS_ERROR = 'BOOKING/GET_TRIP_REVIEWS_ERROR';
export const RESET_TRIP_DETAIL_DATA = 'BOOKING/RESET_TRIP_DETAIL_DATA';
export const BOOKING_STEP = {
  SELECT_SEAT: 1,
  SELECT_PICK_UP_AREA: 2,
  SELECT_DROP_OFF_AREA: 3,
  // SELECT_AREA_SUMMARY: 4,
  CUSTOMER_INFO: 4,
};
export const BOOKING_TYPE = {
  ONLINE: 'ONLINE', // chon so do ghe
  REGISTER: 'REGISTER', // online ko so do ghe
  CALLING: 'CALLING', // dat qua cs
  DEFAULT: 'DEFAULT', // lien he nha xe
};
export const VXR_CONTACT_INFO = {
  SOUTH: {
    NAME: {
      'vi-VN': 'VP. Miền nam',
      'en-US': 'South office',
    },
  },
  NORTH: {
    NAME: {
      'vi-VN': 'VP. Miền bắc',
      'en-US': 'North office',
    },
  },
};

export const DAY_OF_WEEK = {
  Mon: {
    'vi-VN': 'Thứ 2',
    'en-US': 'Monday',
  },
  Tue: {
    'vi-VN': 'Thứ 3',
    'en-US': 'Tuesday',
  },
  Wed: {
    'vi-VN': 'Thứ 4',
    'en-US': 'Wednesday',
  },
  Thu: {
    'vi-VN': 'Thứ 5',
    'en-US': 'Thursday',
  },
  Fri: {
    'vi-VN': 'Thứ 6',
    'en-US': 'Friday',
  },
  Sat: {
    'vi-VN': 'Thứ 7',
    'en-US': 'Saturday',
  },
  Sun: {
    'vi-VN': 'Chủ Nhật',
    'en-US': 'Sunday',
  },
};

export const GET_VXR_HOTLINE = 'GET_VXR_HOTLINE';
export const GET_VXR_HOTLINE_SUCCESS = 'GET_VXR_HOTLINE_SUCCESS';
export const GET_VXR_HOTLINE_ERROR = 'GET_VXR_HOTLINE_ERROR';
// GA Event
export const GA_MAIN_BOOKING_EVENT = 'BOOKING_COMPANY_DETAIL/GA_MAIN_BOOKING_EVENT';
export const GA_MAIN_REGISTER_BOOKING_EVENT = 'BOOKING_COMPANY_DETAIL/GA_MAIN_REGISTER_BOOKING_EVENT';
export const GA_MAIN_PHONE_CALL_BOOKING_EVENT = 'BOOKING_COMPANY_DETAIL/GA_MAIN_PHONE_CALL_BOOKING_EVENT';
export const GA_BOOKING_BOARDING_POINT_SELECTION_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_BOARDING_POINT_SELECTION_EVENT';
export const GA_BOOKING_BOARDING_POINT_SELECTION_TYPE_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_BOARDING_POINT_SELECTION_TYPE_EVENT';
export const GA_BOOKING_DROPPING_POINT_SELECTION_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_DROPPING_POINT_SELECTION_EVENT';
export const GA_BOOKING_DROPPING_POINT_SELECTION_TYPE_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_DROPPING_POINT_SELECTION_TYPE_EVENT';
export const GA_BOOKING_SERVICE_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_SERVICE_EVENT';
export const GA_BOOKING_CONTACT_INFO_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_CONTACT_INFO_EVENT';
export const GA_BOOKING_CONTACT_INFO_TYPE_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_CONTACT_INFO_TYPE_EVENT';
export const GA_BOOKING_EDIT_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BOOKING_EDIT_EVENT';
export const GA_BOOKING_STEP_EVENT = {
  MAIN_BOOKING: 'main booking',
};
export const GA_MAIN_BOOKING_EVENT_CATEGORY = 'main booking: seatmap';
export const GA_MAIN_REGISTER_BOOKING_EVENT_CATEGORY = 'main booking: no seatmap';
export const GA_MAIN_PHONE_CALL_BOOKING_EVENT_CATEGORY = 'main booking: call booking';
export const GA_BOOKING_BOARDING_POINT_SELECTION_EVENT_CATEGORY = 'Boarding point selection';
export const GA_BOOKING_DROPPING_POINT_SELECTION_EVENT_CATEGORY = 'Dropping point selection';
export const GA_BOOKING_SERVICE_CATEGORY = 'services';
export const GA_BOOKING_CONTACT_INFO_CATEGORY = 'Contact info';
export const GA_BOOKING_EDIT_EVENT_CATEGORY = 'Booking info';
// GTM
export const GTM_PRODUCT_DETAIL_VIEW = 'BOOKING_COMPANY_DETAIL/GTM_PRODUCT_DETAIL_VIEW';
export const GTM_ADD_TO_CARD = 'BOOKING_COMPANY_DETAIL/GTM_ADD_TO_CARD';

export const MASK_SEAT_TYPE = {
  0: 'BLANK',
  1: 'DRIVER',
  2: 'SUB_DRIVER',
  3: 'TOILET',
  4: 'DOOR',
}

export const SEAT_TYPE_VALUE = {
  BLANK: 0,
  DRIVER: 4,
  SUB_DRIVER: 5,
  TOILET: 9,
  DOOR: 8,
}
