export const GET_BANNERS = 'BANNER/GET_BANNERS';
export const GET_BANNERS_SUCCESS = 'BANNER/GET_BANNERS_SUCCESS';
export const GET_BANNERS_FAIL = 'BANNER/GET_BANNERS_FAIL';

export const BANNER_PAGE = {
  HOME_PAGE: '1',
  ROUTE_PAGE: '2',
  BUS_OPERATOR_PAGE: '3',
  BUS_STATION_PAGE: '4',
  PAYMENT_PAGE: '5',
  POPUP: '6',
}
