export const GET_BOOKING_INFO = 'PAYMENT_RESULTS/GET_BOOKING_INFO';
export const GET_BOOKING_INFO_SUCCESS = 'PAYMENT_RESULTS/GET_BOOKING_INFO_SUCCESS';
export const GET_BOOKING_INFO_ERROR = 'PAYMENT_RESULTS/GET_BOOKING_INFO_ERROR';
// GTM
export const GTM_PURCHASE_COMPLETE = 'PAYMENT_RESULTS/GTM_PURCHASE_COMPLETE';
// GA
export const GA_PAYMENT_FAILED_EVENT = 'PAYMENT_RESULTS/GA_PAYMENT_FAILED_EVENT';
export const GA_PAYMENT_FAILED_EVENT_CATEGORY = 'Giao dịch thất bại';

export const GA_BOOKING_CANCLED_EVENT = 'PAYMENT_RESULTS/GA_BOOKING_CANCLED_EVENT';
export const GA_BOOKING_CANCLED_EVENT_CATEGORY = 'Giao dịch quá hạn';

export const GA_PAYMENT_PROCESSING_EVENT = 'PAYMENT_RESULTS/GA_PAYMENT_PROCESSING_EVENT';
export const GA_PAYMENT_PROCESSING_EVENT_CATEGORY = 'Giao dịch đang xử lí';

export const GA_PAYMENT_SUCCESS_EVENT = 'PAYMENT_RESULTS/GA_PAYMENT_SUCCESS_EVENT';
export const GA_PAYMENT_SUCCESS_EVENT_CATEGORY = 'Thanh toán thành công';

export const GA_RESERVED_SUCCESS_EVENT = 'PAYMENT_RESULTS/GA_RESERVED_SUCCESS_EVENT';
export const GA_RESERVED_SUCCESS_EVENT_CATEGORY = 'Đặt chỗ thành công';
