export default {
    'OPERATOR_LIMOUSINE_GIUONG_NAM_DOI': 1,
    'OPERATOR_LIMOUSINE_GIUONG_NAM': 2,
    'OPERATOR_LIMOUSINE_GHE_NGOI': 3,
    'OPERATOR_LIMOUSINE_GHE_NAM': 4,
    'OPERATOR_LIMOUSINE': 5,

    'OPERATOR_GIUONG_NAM_DOI': 6,
    'OPERATOR_GIUONG_NAM': 7,
    'OPERATOR_GHE_NGOI': 8,
    'OPERATOR_GHE_NAM': 9,
    'OPERATOR': 10,

    'COMMON_LIMOUSINE_GIUONG_NAM_DOI': 11,
    'COMMON_LIMOUSINE_GIUONG_NAM': 12,
    'COMMON_LIMOUSINE_GHE_NGOI': 13,
    'COMMON_LIMOUSINE_GHE_NAM': 14,
    'COMMON_LIMOUSINE': 15,

    'COMMON_GIUONG_NAM_DOI': 16,
    'COMMON_GIUONG_NAM': 17,
    'COMMON_GHE_NGOI': 18,
    'COMMON_GHE_NAM': 19,
    'COMMON': 20,

    'BUS_OPERATOR': 21
}