export default {
    'OPERATOR_LIMOUSINE_DOUBLE_SLEEPER': 1,
    'OPERATOR_LIMOUSINE_SLEEPER': 2,
    'OPERATOR_LIMOUSINE_SEATER': 3,
    'OPERATOR_LIMOUSINE_SEMI_SLEEPER': 4,
    'OPERATOR_LIMOUSINE': 5,

    'OPERATOR_DOUBLE_SLEEPER': 6,
    'OPERATOR_SLEEPER': 7,
    'OPERATOR_SEATER': 8,
    'OPERATOR_SEMI_SLEEPER': 9,
    'OPERATOR': 10,

    'COMMON_LIMOUSINE_DOUBLE_SLEEPER': 11,
    'COMMON_LIMOUSINE_SLEEPER': 12,
    'COMMON_LIMOUSINE_SEATER': 13,
    'COMMON_LIMOUSINE_SEMI_SLEEPER': 14,
    'COMMON_LIMOUSINE': 15,

    'COMMON_DOUBLE_SLEEPER': 16,
    'COMMON_SLEEPER': 17,
    'COMMON_SEATER': 18,
    'COMMON_SEMI_SLEEPER': 19,
    'COMMON': 20,

    'BUS_OPERATOR': 21
}