#image: node-builder:10-alpine
image: deployer:latest
services:
  - docker:dind
before_script:
  - docker version
  - env
  - sh /app/active.sh
variables:
  GIT_SSL_NO_VERIFY: "1"
  BUILD_IMAGE: gcr.io/vexere-218206/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  TAG_IMAGE: gcr.io/vexere-218206/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  RELEASE_IMAGE: gcr.io/vexere-218206/$CI_PROJECT_NAME:latest

stages:
  - build
  - release-uat
  - build-canary
  - release-canary
  - release

build:
  stage: build
  variables:
    ENV: 'uat'
  script:
    - docker build -t $BUILD_IMAGE .
    - docker  push  $BUILD_IMAGE
  only:
    - develop
  tags:
    - docker-builder

release-uat:
  stage: release-uat
  script:
  - cd ./k8s
  - sed -i "s/latest/"$CI_COMMIT_SHA"/g" uat-nextvxr-dev.yml
  - cat uat-nextvxr-dev.yml
  - kubectl apply -f uat-nextvxr-dev.yml
  only:
  - develop
  tags:
  - docker-builder

build-canary:
  stage: build-canary
  variables:
    ENV: 'uat'
  script:
  - docker build -t $BUILD_IMAGE .
  - docker push $BUILD_IMAGE
  only:
  - master
  tags:
  - docker-builder

release-canary:
  stage: release-canary
  script:
  - cd ./k8s
  - sed -i "s/latest/"$CI_COMMIT_SHA"/g" canary-nextvxr-dev.yml
  - cat canary-nextvxr-dev.yml
  - kubectl apply -f canary-nextvxr-dev.yml
  only:
  - master
  tags:
  - docker-builder

release:
  stage: release
  script:
  - docker tag $BUILD_IMAGE $TAG_IMAGE
  - docker tag $BUILD_IMAGE $RELEASE_IMAGE
  - docker push $TAG_IMAGE
  - docker push $RELEASE_IMAGE
  - cd ./k8s
  - sed -i "s/latest/"$CI_COMMIT_TAG"/g" production-nextvxr-dev.yml
  - cat production-nextvxr-dev.yml
  - kubectl apply -f production-nextvxr-dev.yml
  only:
  - /^release-.*$/
  tags:
  - docker-builder
