export const GET_COMPANY_INFO = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_INFO';
export const GET_COMPANY_INFO_SUCCESS = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_INFO_SUCCESS';
export const GET_COMPANY_INFO_ERROR = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_INFO_ERROR';
export const GET_COMPANY_IMAGE_SUCCESS = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_IMAGE_SUCCESS';
export const GET_COMPANY_IMAGE_ERROR = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_IMAGE_ERROR';
export const GET_CANCELLATION_POLICY = 'BOOKING_COMPANY_DETAIL/GET_CANCELLATION_POLICY';
export const GET_CANCELLATION_POLICY_SUCCESS = 'BOOKING_COMPANY_DETAIL/GET_CANCELLATION_POLICY_SUCCESS';
export const GET_CANCELLATION_POLICY_ERROR = 'BOOKING_COMPANY_DETAIL/GET_CANCELLATION_POLICY_ERROR';
export const GET_COMPANY_UTILITY = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_UTILITY';
export const GET_COMPANY_UTILITY_SUCCESS = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_UTILITY_SUCCESS';
export const GET_COMPANY_UTILITY_ERROR = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_UTILITY_ERROR';
export const GET_COMPANY_SUMMARY_INFO_SUCCESS = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_SUMMARY_INFO_SUCCESS';
export const GET_COMPANY_SUMMARY_INFO_ERROR = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_SUMMARY_INFO_ERROR';
export const GET_COMPANY_REVIEW = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_REVIEW';
export const GET_COMPANY_REVIEW_SUCCESS = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_REVIEW_SUCCESS';
export const GET_COMPANY_REVIEW_ERROR = 'BOOKING_COMPANY_DETAIL/GET_COMPANY_REVIEW_ERROR';
export const CLEAR_COMPANY_REVIEW_DATA = 'BOOKING_COMPANY_DETAIL/CLEAR_COMPANY_REVIEW_DATA';
export const TAB_KEYS = {
  AMENITIES: 'AMENITIES',
  REFUND_POLICY: 'REFUND_POLICY',
  REVIEWS: 'REVIEWS',
};
// GA Event
export const GA_BUS_INFO_EVENT = 'BOOKING_COMPANY_DETAIL/GA_BUS_INFO_EVENT';
export const GA_BUS_INFO_EVENT_CLICK = 'BOOKING_COMPANY_DETAIL/GA_BUS_INFO_EVENT_CLICK';
export const GA_BUS_INFO_EVENT_CATEGORY = 'bus info';
export const GA_TAB_VALUE = {
  AMENITIES: 'Amenities tab',
  REFUND_POLICY: 'Cancellation policy tab',
  REVIEWS: 'Rating tab',
};
